apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blueprint.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "blueprint.name" . }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blueprint.name" . }}
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "blueprint.name" . }}
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: api
          image: {{ .Values.image.api }}
          imagePullPolicy: IfNotPresent
          env:
            {{- range $key, $value := .Values.env.API }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.api.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources: {{- toYaml .Values.resources.api | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blueprint.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "blueprint.name" . }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app.kubernetes.io/name: {{ include "blueprint.name" . }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
