name: Test All

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run API unit tests
        run: pnpm --filter ./apps/api test
      - name: Upload unit coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: apps/api/coverage/unit

  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run OpenAPI contract tests
        run: pnpm --filter ./apps/api test:contract

  e2e-web:
    runs-on: ubuntu-latest
    services:
      web:
        image: node:lts
        ports:
          - "3000:3000"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm --filter ./apps/web exec playwright install --with-deps
      - name: Run web E2E tests
        env:
          PLAYWRIGHT_API_ORIGIN: http://localhost:4000
        run: pnpm --filter ./apps/web test:e2e
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report

  e2e-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter version
        run: flutter --version
      - name: Install Dart dependencies
        run: flutter pub get
        working-directory: apps/mobile
      - name: Run Flutter tests
        run: flutter test
        working-directory: apps/mobile
